KAFKA-15837: Throw error on use of Consumer.poll(long timeout)
apache/kafka pull request #14773
Opened 2023-11-16 01:03 UTC by kirktrue

Per KIP-266, the `Consumer.poll(long timeout)` method was deprecated in 2.0.0. The default implementation of `Consumer.poll(long timeout)` now throws a `KafkaException`, and the known implementations have been removed to fall back to the default.

2023-11-16 08:31 UTC, AndrewJSchofield requested changes

2023-11-16 08:31 UTC, AndrewJSchofield commented on clients/src/main/java/org/apache/kafka/clients/consumer/Consumer.java
> +        throw new KafkaException("This version of poll() is no longer supported. See KIP-266 (https://cwiki.apache.org/confluence/x/5kiHB) for more information.");
I think we cannot do this in AK 3.7 for the existing consumer. I suggest that the exception is thrown in `AsyncKafkaConsumer` only and the behaviour remains unchanged for the legacy consumer.

2023-11-21 15:20 UTC, AndrewJSchofield commented
This PR has been superseded and can be closed.

2023-11-21 17:53 UTC, kirktrue commented
@lucasbru / @cadonna—can we add the `ctr` label for posterity? Then I'll close it.

2023-11-21 17:54 UTC, cadonna commented
Done!
I think this PR can be closed, because it was superseded by https://github.com/apache/kafka/pull/14810

2023-11-21 17:56 UTC, kirktrue commented
> Done! I think this PR can be closed, because it was superseded by #14810

Yes, I will close it with this very comment 😉

2023-11-21 17:56 UTC, closed without merging