KAFKA-15842: Correct handling of KafkaConsumer.committed for new consumer
apache/kafka pull request #14859
Opened 2023-11-28 22:11 UTC by AndrewJSchofield

This PR fixes some details of the interface to KafkaConsumer.committed which were different between the existing consumer and the new consumer.

Adds a unit test that validates the behaviour is the same for both consumer implementations.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

2023-11-29 09:20 UTC, AndrewJSchofield commented
Closing and reopening PR to retry failed build.

2023-11-29 14:00 UTC, AndrewJSchofield commented
https://issues.apache.org/jira/browse/KAFKA-15932 opened for flaky test.

2023-11-30 20:29 UTC, kirktrue requested changes
Thanks @AndrewJSchofield!

Thanks for the fix and the associated clean up. One minor nit-ty change requested.

2023-11-30 20:29 UTC, kirktrue commented on checkstyle/suppressions.xml
> -              files="(AbstractFetch|Sender|SenderTest|ConsumerCoordinator|KafkaConsumer|PrototypeAsyncConsumer|KafkaProducer|Utils|TransactionManager|TransactionManagerTest|KafkaAdminClient|NetworkCl
Thank you for this clean up!

2023-11-30 20:29 UTC, kirktrue commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/AsyncKafkaConsumer.java
> +                    "committed offset for partitions " + partitions + " could be determined. Try tuning default.api.timeout.ms " +
nit: please replace the literal string `default.api.timeout.ms` with the appropriate constant from `ConsumerConfig` 🥺

2023-11-30 20:29 UTC, kirktrue commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/AsyncKafkaConsumer.java
> +                return Collections.emptyMap();
Does this make a difference, or just a stylistic/pet peeve/optimiz/sation thing?

2023-11-30 20:29 UTC, kirktrue commented on core/src/test/scala/integration/kafka/api/PlaintextConsumerTest.scala
> +  @MethodSource(Array("getTestQuorumAndGroupProtocolParametersGenericGroupProtocolOnly"))
😭

2023-11-30 21:12 UTC, AndrewJSchofield commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/AsyncKafkaConsumer.java
> +                return Collections.emptyMap();
I made it strictly identical to the previous implementation.

2023-12-01 13:35 UTC, cadonna commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/AsyncKafkaConsumer.java
> +                    "committed offset for partitions " + partitions + " could be determined. Try tuning default.api.timeout.ms " +
While I agree with @kirktrue , let's merge this PR and fix this on the side in a follow-up PR.

2023-12-01 13:35 UTC, cadonna approved these changes
Thanks @AndrewJSchofield !

LGTM!

2023-12-01 13:37 UTC, merged