KAFKA-15970 Copy over KIP-951 tests in FetcherTest.java to FetchRequestManagerTest.java
apache/kafka pull request #14916
Opened 2023-12-04 17:37 UTC by msn-tldr

Copying over tests added to FetcherTest.java in [PR](https://github.com/apache/kafka/pull/14685/files#diff-2745b4306d343fd2a5abbf6314c0f8d01d07d7140ab989894ca1a0a17100f02a) to FetchRequestManagerTest.java, so KIP-951 changes have coverage with new consumer being worked as described here 
https://cwiki.apache.org/confluence/display/KAFKA/Consumer+threading+refactor+project+overview

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

2023-12-04 20:14 UTC, AndrewJSchofield requested changes
It's a bit hard to follow, but the overall idea of the tests seems sound.

2023-12-04 20:14 UTC, AndrewJSchofield commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/FetchRequestManagerTest.java
> +        // Next fetch returns an error(due to leadership change) and new leader info is returned. The new leader is a new node, id = 999.
This comment seems quite out of place. The vital line of code is 3283.

2023-12-04 20:14 UTC, AndrewJSchofield commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/FetchRequestManagerTest.java
> +    public void testWhenFetchResponseReturnsWithALeaderShipChangeErrorButNoNewLeaderInformation(Errors error) {
`...ALeadershipChangeError...` please.

2023-12-04 20:14 UTC, AndrewJSchofield commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/FetchRequestManagerTest.java
> +        // Validate metadata is unchanged, as response has missing new leader info.
It's not really missing new leader info, which sounds like a problem. It's just that KIP-951 provides a way to attach the new leader info to the response, and this first test shows the case where that is not being done.

2023-12-05 11:40 UTC, msn-tldr commented
@AndrewJSchofield I have update the comments in the test to make it more readable, hope it helps.

Also i have made same changes to FetcherTest where these tests were originally added.

2023-12-05 11:58 UTC, AndrewJSchofield approved these changes
lgtm

2023-12-05 11:58 UTC, AndrewJSchofield commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/FetcherTest.java
> +        // Verify that metadata-update isn't requested as metadata is considered upto-date.
"up to date"

2023-12-05 17:27 UTC, kirktrue approved these changes
LGTM, assuming the tests pass 😄

2023-12-05 17:44 UTC, wcarlson5 approved these changes

2023-12-05 18:27 UTC, msn-tldr commented
So JDK 17 build failed with following and its unrelated.
https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-14916/5/pipeline/11/

```
org.gradle.internal.remote.internal.ConnectException: Could not connect to server [a99ad330-91c1-4b36-98c1-035d6d718e13 port:35031, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].

	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67)

	at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36)

	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:103)

	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)

	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)

	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

Caused by: java.net.ConnectException: Connection refused

	at java.base/sun.nio.ch.Net.pollConnect(Native Method)

	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)

	at java.base/sun.nio.ch.SocketChannelImpl.finishTimedConnect(SocketChannelImpl.java:1141)

	at java.base/sun.nio.ch.SocketChannelImpl.blockingConnect(SocketChannelImpl.java:1183)

	at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:98)

	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)

	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)

	... 5 more
.....
.....

* What went wrong:

Execution failed for task ':streams:upgrade-system-tests-10:checkstyleTest'.

> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction

   > Failed to run Gradle Worker Daemon

      > Process 'Gradle Worker Daemon 4' finished with non-zero exit value 1
```

2023-12-05 22:02 UTC, wcarlson5 commented
I'll rerun it and see if it gets any further :)

2023-12-06 13:15 UTC, msn-tldr commented
@wcarlson5 thanks! The failures are unrelated in the new build
https://ge.apache.org/s/ul2ost2737xbg/tests/overview?outcome=FAILED

2023-12-06 14:52 UTC, merged

2023-12-09 11:39 UTC, msn-tldr commented
@wcarlson5 thanks!