KAFKA-16272: Update connect_distributed_test.py to support KIP-848’s group protocol config
apache/kafka pull request #15576
Opened 2024-03-21 17:51 UTC by philipnee

Update connect_distributed_test.py to support KIP-848’s group protocol config.  Not all tests are updated because only a subset of it is using the consumer directly.

2024-03-22 04:21 UTC, kirktrue requested changes
Thanks for PR, @philipnee. There are just a couple of places that we're missing the necessary parameters.

2024-03-22 04:21 UTC, kirktrue commented on tests/kafkatest/tests/connect/connect_distributed_test.py
> +    )
We need the `clean` and `connect_protocol` values to be included.

```suggestion
    @matrix(
        clean=[True, False],
        connect_protocol=['sessioned', 'compatible', 'eager'],
        metadata_quorum=[quorum.isolated_kraft],
        use_new_coordinator=[True],
        group_protocol=consumer_group.all_group_protocols
    )
```

2024-03-22 04:21 UTC, kirktrue commented on tests/kafkatest/tests/connect/connect_distributed_test.py
> +    )
Either we need to add the `group_protocol` parameter, or else just remove this new `@matrix`.

```suggestion
```

2024-03-22 04:21 UTC, kirktrue commented on tests/kafkatest/tests/connect/connect_distributed_test.py
>          use_new_coordinator=[True, False]
```suggestion
        use_new_coordinator=[False]
```

2024-03-22 04:21 UTC, kirktrue commented on tests/kafkatest/tests/connect/connect_distributed_test.py
> +    )
We still need the `connect_protocol` here:

```suggestion
    @matrix(
        connect_protocol=['sessioned', 'compatible', 'eager'],
        metadata_quorum=[quorum.isolated_kraft],
        use_new_coordinator=[True],
        group_protocol=consumer_group.all_group_protocols
    )
```

2024-03-22 05:52 UTC, vamossagar12 commented
@philipnee , I had assigned the ticket to myself and had started working on it (was in the process of testing it actually). Anyways since you have the PR, so you would want to continue on this then?

2024-03-22 15:20 UTC, philipnee commented
Hey @kirktrue - Thanks for the review.  I didn't put in the parameters because these tests don't configure the consumer directly.  I think if can modify the connector to use the latest consumer, then it would make sense to put in these params.

2024-03-22 15:22 UTC, philipnee commented
@vamossagar12 - Hey - The connector test still requires a bit of parametrization on the connector side.  If you feel like you have the bandwidth to handle this feel free to continue with the work.  The current state of PR only parameterizes the test that are using the consumer directly.

2024-03-22 15:51 UTC, vamossagar12 commented
@philipnee , thanks .ok will continue. Yeah I can send out a pr next week for this.

2024-03-22 16:28 UTC, philipnee commented
Thanks @vamossagar12 - You can either create a new jira ticket for fixing these connectors or using the existing tickets.  Maybe we should create a new ticket for new connector interface in the system tests as it is a bit more involving than just parametrizing the tests.

2024-03-25 09:31 UTC, vamossagar12 commented
@philipnee , here's the PR that I created: https://github.com/apache/kafka/pull/15594. Actually I looked at your changes now and it appears that the changes in the new PR consists of all the changes in this PR plus additional connect changes. Let me know if we can continue working on the new one? I will loop in connect experts as well once the basic structure is reviewed.

2024-03-25 23:18 UTC, philipnee commented
@kirktrue @lucasbru - mind taking a second look? For this specific PR I only modified the tests using console consumer that's why several tests cases were omitted.

2024-03-26 09:53 UTC, lucasbru commented
@philipnee Could you please address/respond to @kirktrue's comments. We seem to be dropping parameters here, and some test cases with the new coordinator seem to be duplicated after the change.

2024-03-26 18:03 UTC, philipnee commented
@lucasbru @kirktrue - Sorry for the oversight. I pushed out the changes to address Kirk's comment.

2024-03-27 11:10 UTC, lucasbru approved these changes
LGTM. thanks

2024-03-27 11:10 UTC, merged