KAFKA-16558 Implemented HeartbeatRequestState toStringBase() and added a test for it
apache/kafka pull request #16124
Opened 2024-05-29 15:25 UTC by brenden20

I implemented HeartbeatRequestState.toStringBase(), I also added 2 getter methods for testing purposes. I added a test for the new method, which is passing. Test may/may not be necessary, added just in case.

2024-05-30 19:24 UTC, kirktrue requested changes
Thanks @brenden20! This looks good. Minor nits only.

2024-05-30 19:24 UTC, kirktrue commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManagerTest.java
> +        HeartbeatRequestState heartbeatRequestState1 = new HeartbeatRequestState(
Super nit: we can drop the `1` at the end of the variable name, right?

```suggestion
        HeartbeatRequestState heartbeatRequestState = new HeartbeatRequestState(
```

2024-05-30 19:24 UTC, kirktrue commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManagerTest.java
> +                "org.apache.kafka.clients.consumer.internals.HeartbeatRequestManager$HeartbeatRequestState",
Perhaps we could make `HeartbeatRequestState` package-protected, then we could do this:

```suggestion
                HeartbeatRequestManager.HeartbeatRequestState.class.getName(),
```

2024-05-30 19:24 UTC, kirktrue commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManager.java
> +            return this.heartbeatTimer;
```suggestion
            return heartbeatTimer;
```

2024-05-30 19:24 UTC, kirktrue commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManager.java
> +            return this.heartbeatIntervalMs;
```suggestion
            return heartbeatIntervalMs;
```

2024-05-30 19:37 UTC, kirktrue commented
The test failures are unrelated, FWIW.

2024-05-30 20:19 UTC, brenden20 commented
@kirktrue thank you for the suggestions, I have implemented and pushed your suggestions. Let me know if everything looks good!

2024-06-02 20:15 UTC, philipnee commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManager.java
> +    protected static class HeartbeatRequestState extends RequestState {
this is for testing purpose right? add a // Visible for testing comment

2024-06-02 20:20 UTC, philipnee commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManagerTest.java
> +                10,
extract this out as a variable for testing later

2024-06-02 20:20 UTC, philipnee commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManagerTest.java
> +                ", heartbeatTimer=" + heartbeatRequestState.heartbeatTimer() +
can we just apply `time.timer(heartbeatIntervalMs)`

2024-06-02 20:20 UTC, philipnee commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManagerTest.java
> +                ", heartbeatIntervalMs=" + heartbeatRequestState.heartbeatIntervalMs();
Just test against `heartbeatIntervalMs`

2024-06-02 20:21 UTC, philipnee commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManager.java
> +        // Visible for testing
i don't think we need the `heartbeatTimer()` and `heartbeatIntervalMs()` here.  see the comment below.

2024-06-02 20:22 UTC, philipnee commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManagerTest.java
> +        final long retryBackoffMs = 100;
i think we should try to consistently apply final to all variables if we want to use final.

2024-06-02 20:46 UTC, philipnee commented
hi @brenden20 - left some comments. lmk what do you think.

2024-06-05 18:13 UTC, kirktrue approved these changes
LGTM!

2024-06-05 18:14 UTC, kirktrue commented
@brenden20—can we mark this _Ready for review_?

2024-06-05 18:20 UTC, brenden20 commented
Marked ready to review

2024-06-11 12:18 UTC, philipnee approved these changes
lgtm thanks for the patch

2024-06-17 17:13 UTC, brenden20 commented
Merge issues, moved PR to https://github.com/apache/kafka/pull/16373 and closing this one

2024-06-17 17:13 UTC, closed without merging