KAFKA-16356 GroupRebalanceConfig: rebalanceTimeoutMs updated to commitTimeoutDuringReconciliation
apache/kafka pull request #16334
Opened 2024-06-13 20:15 UTC by linu-shibu

As mentioned in the ticket, the config property name "rebalanceTimeoutMs" is misleading since the property only handles the client's commit portion of the process.It is used in MembershipManagerImpl as a means to limit the client's efforts in the case where it is repeatedly trying to commit but failing. Considering the same, the property name has been updated to "commitTimeoutDuringReconciliation" (suggested in ticket) in GroupRebalanceConfig and in all other classes where the property/variable is used

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

2024-06-13 20:18 UTC, linu-shibu commented
@kirktrue is this what was intended? Since you mentioned that the property in ClientConfig object is used only for limiting client efforts to commit, I have changed the property name in the config file. Please review this and provide some feedback

2024-06-17 21:38 UTC, kirktrue commented
My apologies, @linu-shibu.

I think the consensus was to change [`MembershipManagerImpl`'s](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/MembershipManagerImpl.java) `rebalanceTimeoutMs` instance variable to `commitTimeoutDuringReconciliation`. We don't want to change any other code at this point.

Thanks!

2024-06-18 20:28 UTC, linu-shibu commented
> My apologies, @linu-shibu.
> 
> I think the consensus was to change [`MembershipManagerImpl`'s](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/MembershipManagerImpl.java) `rebalanceTimeoutMs` instance variable to `commitTimeoutDuringReconciliation`. We don't want to change any other code at this point.
> 
> Thanks!

Updated accordingly, please review again

2024-07-23 10:51 UTC, chia7712 reviewed
@linu-shibu thanks for this nice patch

2024-07-23 10:51 UTC, chia7712 commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/MembershipManagerImpl.java
>       * when a new assignment is received, that is retried until it succeeds, fails with a
Could you please update docs also?

2024-07-24 23:54 UTC, kirktrue requested changes
Thanks for the updates, @linu-shibu! This looks very close!

As @chia7712 requested, please update use of the phrase "rebalance timeout" (or similar) in the comments/JavaDoc of this file.

Thanks!

2024-07-25 20:59 UTC, linu-shibu commented
Updated java docs and comments

2024-07-29 12:58 UTC, chia7712 approved these changes
LGTM

2024-07-29 22:15 UTC, kirktrue requested changes
Thanks @linu-shibu.

There's an extra space in the `commitTimeoutDuringReconciliation` JavaDoc. Other than that everything's LGTM.

Thanks!

2024-07-29 22:15 UTC, kirktrue commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/MembershipManagerImpl.java
> +     * Reconciliation commit timeout . To be used as time limit for the commit request issued
Super minor nit...

```suggestion
     * Reconciliation commit timeout. To be used as time limit for the commit request issued
```

2024-07-31 10:49 UTC, chia7712 commented
@kirktrue Could you please take a look at it? I'd like to merge it with your approve.

2024-07-31 16:45 UTC, kirktrue approved these changes
LGTM! 👍

2024-07-31 16:51 UTC, merged