KAFKA-16558 Implemented HeartbeatRequestState toStringBase() and added a test for it
apache/kafka pull request #16373
Opened 2024-06-17 17:13 UTC by brenden20

In this PR I have implemented HeartbeatRequestState.toStringBase() and added a test for it in HeartbeatRequestManagerTest

2024-07-01 22:44 UTC, kirktrue requested changes
Thanks for the PR, @brenden20! I have only the one minor change request, but it looks good otherwise!

2024-07-01 22:44 UTC, kirktrue commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManager.java
> +                    ", heartbeatTimer=" + heartbeatTimer +
Much to my chagrin, `Timer` does not override `toString()` to provide any insight.

[Elsewhere in the code base](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/TimedRequestState.java#L67-L70), we took the approach of exposing the remaining time in a fashion such as:

```java
@Override
protected String toStringBase() {
    return super.toStringBase() + ", remainingMs=" + heartbeatTimer.remainingMs();
}
```

2024-07-04 03:59 UTC, brenden20 commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManager.java
> +                    ", heartbeatTimer=" + heartbeatTimer +
I made this change now, just want to make sure I did it correctly

2024-07-20 00:28 UTC, mjsax commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManagerTest.java
> +                ", remainingMs=" + heartbeatRequestState.heartbeatTimer().remainingMs() +
We should not call `heartbeatRequestState.heartbeatTimer().remainingMs()` here -- it defeats the purpose of the test. Assume we except `remainingMs:500` but there is a bug -- this call will compute the incorrect `target` and we would compare it to itself.

We should just put down the expected target hard-coded (or compute is some different way if we need some flexibility)

For `DEFAULT_HEARTBEAT_INTERVAL_MS` is fine as this is a `final` variable.

2024-07-20 00:29 UTC, mjsax commented on clients/src/main/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManager.java
> +        Timer heartbeatTimer() {
Cf my other comment -- I think we don't need to add this.

2024-07-22 15:30 UTC, brenden20 commented on clients/src/test/java/org/apache/kafka/clients/consumer/internals/HeartbeatRequestManagerTest.java
> +                ", remainingMs=" + heartbeatRequestState.heartbeatTimer().remainingMs() +
I see your point, I have updated the test now. Since we compute `target` right after creating a `RequestState`, I thought for the test it would be appropriate to hard-code `remainingMs` to be equal to `DEFAULT_HEARTBEAT_INTERVAL_MS`. I have also removed the `heartbeatTimer()` method.

2024-07-22 15:30 UTC, brenden20 commented
@mjsax thank you for the review! I have implemented your suggestions, let me know how it looks!

2024-07-22 22:38 UTC, mjsax approved these changes
LGTM.

2024-07-23 08:47 UTC, AndrewJSchofield approved these changes

2024-07-25 20:27 UTC, merged

2024-07-25 20:27 UTC, mjsax commented
Thanks for the PR @brenden20. Merged to `trunk`.