KAFKA-16907: Fix RaftUtil's type complexity
apache/kafka pull request #16831
Opened 2024-08-08 04:54 UTC by frankvicky

JIRA: [KAFKA-16907](https://issues.apache.org/jira/browse/KAFKA-16907)

This PR aims to fix the `ClassDataAbstractionCoupling` and `ClassFanOutComplexity` issues in RaftUtils.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

2024-08-22 07:10 UTC, frankvicky commented
Will fix conflicts after 3.9 RC

2024-10-08 08:40 UTC, frankvicky commented
Hi @jsancio,
Could you please take a look at this PR when you have some time?  
Many thanks! 😺

2024-12-01 08:52 UTC, frankvicky commented
Hi @chia7712 
Could you please take a look?
Many thanks 😺

2024-12-17 19:33 UTC, ahuang98 commented on raft/src/main/java/org/apache/kafka/raft/utils/VoteRpc.java
> +    public static AddRaftVoterRequestData addVoterRequest(
VoteRequest, VoteResponse should be part of the VoteRPCs, but not addVoter, removeVoter, updateVoter. Perhaps we want a DynamicReconfigRpc class for those

2024-12-17 19:35 UTC, ahuang98 commented on raft/src/test/java/org/apache/kafka/raft/KafkaNetworkChannelTest.java
> +                FetchRequestData request = FetchRpc.singletonFetchRequest(topicPartition, topicId, fetchPartition ->
I wouldn't be upset having both Fetch and FetchSnapshot in the same class. But I guess same argument could be made for Begin and End Quorum (and I see how naming might get more difficult)

2024-12-17 19:36 UTC, ahuang98 requested changes
Approach looks reasonable to me! Main request is that the dynamic reconfig related RPCs are broken out of VoteRPC

2025-01-13 22:18 UTC, ahuang98 commented on raft/src/main/java/org/apache/kafka/raft/utils/BeginQuorumEpochRpc.java
> +                   data.topics().get(0).partitions().get(0).partitionIndex() == topicPartition.partition();
spacing looks off

2025-01-13 22:18 UTC, ahuang98 commented on raft/src/main/java/org/apache/kafka/raft/utils/DescribeQuorumRpc.java
> +                .setTopics(
looks like these are all 8 vs 4 spaces

2025-01-14 00:49 UTC, frankvicky commented on raft/src/main/java/org/apache/kafka/raft/utils/BeginQuorumEpochRpc.java
> +                   data.topics().get(0).partitions().get(0).partitionIndex() == topicPartition.partition();
It seems like an issue of idea format config.
I have adjusted it.

2025-01-31 16:29 UTC, ahuang98 commented on raft/src/main/java/org/apache/kafka/raft/utils/DescribeQuorumRpc.java
> +                                    .setObservers(toReplicaStates(apiVersion, leaderId, observers, currentTimeMs))))));
style nit: I know this was carried over from the old code, but maybe better to have each closing parenthesis on its own new line

2025-01-31 16:31 UTC, ahuang98 approved these changes
other than style nit, looks good to me 
@jsancio to help merge!

2025-02-01 02:53 UTC, frankvicky commented on raft/src/main/java/org/apache/kafka/raft/utils/DescribeQuorumRpc.java
> +                                    .setObservers(toReplicaStates(apiVersion, leaderId, observers, currentTimeMs))))));
I will take a look 😺

2025-08-31 03:41 UTC, closed without merging