KAFKA-3590: Handle not-enough-replicas errors when writing to offsets topic
apache/kafka pull request #1859
Opened 2016-09-15 03:28 UTC by hachikuji

2016-09-22 22:24 UTC, ijuma commented on core/src/main/scala/kafka/coordinator/GroupMetadataManager.scala
> +              s"due to unexpected error code: ${statusError.code}")
Why are we not using `exceptionName` here?

2016-09-22 22:31 UTC, ijuma commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertEquals(Errors.NONE, maybeError.get)
You will get better errors if you replace both lines above with:

```scala
assertEquals(Some(Errors.NONE), maybeError)
```

2016-09-22 22:32 UTC, ijuma commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertStoreGroupErrorMapping(Errors.INVALID_FETCH_SIZE, Errors.UNKNOWN)
How come we use `UNKNOWN` for `MESSAGE_TOO_LARGE` for example?

2016-09-22 22:34 UTC, ijuma commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertEquals(expectedError, maybeError.get)
Same as elsewhere, if you assert that the result is a `Some(...)`, you get a better error than the `assertTrue(foo.isDefined)`. And save a line too. ;)

2016-09-22 22:34 UTC, ijuma commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertEquals(Errors.NONE, maybeError.get)
Similar as the other messages above.

2016-09-22 22:35 UTC, ijuma requested changes
Minor suggestions and a couple of questions, looks good otherwise.

2016-09-23 00:10 UTC, hachikuji commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertEquals(Errors.NONE, maybeError.get)
Ack

2016-09-23 00:19 UTC, hachikuji commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertStoreGroupErrorMapping(Errors.INVALID_FETCH_SIZE, Errors.UNKNOWN)
I was a little surprised to see this also. @guozhangwang can probably clarify, but this is basically an unrecoverable error for the consumer, so I think the idea is to return an error to the client which will cause it to crash, but which doesn't expose the internal storage mechanism.

2016-09-23 00:32 UTC, hachikuji commented on core/src/main/scala/kafka/coordinator/GroupMetadataManager.scala
> +              s"due to unexpected error code: ${statusError.code}")
Can't think of a good reason. I'll change it.

2016-09-23 00:37 UTC, hachikuji commented
@ijuma Ready for another look when you have a chance.

2016-09-23 00:54 UTC, ijuma commented
LGTM

2016-09-23 02:14 UTC, guozhangwang commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertStoreGroupErrorMapping(Errors.INVALID_FETCH_SIZE, Errors.UNKNOWN)
@hachikuji Shouldn't this be mapped to `Errors.INVALID_COMMIT_OFFSET_SIZE`?

2016-09-23 02:16 UTC, hachikuji commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertStoreGroupErrorMapping(Errors.INVALID_FETCH_SIZE, Errors.UNKNOWN)
@guozhangwang This case is for persistence of group metadata.

2016-09-23 19:55 UTC, guozhangwang commented on core/src/test/scala/unit/kafka/coordinator/GroupMetadataManagerTest.scala
> +    assertStoreGroupErrorMapping(Errors.INVALID_FETCH_SIZE, Errors.UNKNOWN)
Got it. LGTM.

2016-09-23 20:14 UTC, closed without merging

2016-09-23 20:15 UTC, hachikuji commented
Merged to trunk and 0.10.1.