KAFKA-3038; Future'based pseudo-async controller
apache/kafka pull request #2213
Opened 2016-12-06 11:26 UTC by resetius

2016-12-06 11:28 UTC, resetius commented
This PR based on https://github.com/apache/kafka/pull/750 but it uses Futures so code is match more simple.
Tested on high load cluster with ~100K partitions. The speedup of leader election is up to 100x.

2016-12-06 11:48 UTC, ataraxer commented on core/src/main/scala/kafka/controller/PartitionStateMachine.scala
> +    val futureOfList = Future.sequence(listOfFutures)
[Реализация](https://github.yandex-team.ru/gist/ataraxer/3bbf9fd17815b57adeceb3f60bfa526d).
Тут.

2016-12-06 11:48 UTC, ataraxer commented on core/src/main/scala/kafka/controller/ReplicaStateMachine.scala
> +        val futureOfList = Future.sequence(listOfFutures)
И тут.

2016-12-06 11:54 UTC, ataraxer commented on core/src/main/scala/kafka/controller/PartitionStateMachine.scala
> +    val futureOfList = Future.sequence(listOfFutures)
`Futures.sequence` [folds](https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/Future.scala#L499) over a provided list of futures chaining them via `flatMap` which doesn't allow GC to collect them individually after completion. Here's a simple implementation that doesn't has this problem: [gist](https://gist.github.com/ataraxer/7d49e49e90ba025dbcdf679c39297741).

2016-12-06 11:56 UTC, ataraxer requested changes
Sorry, hadn't noticed that this isn't internal GitHub Enterprise when following a link, please disregard previous comments.

2016-12-06 11:56 UTC, ataraxer commented on core/src/main/scala/kafka/controller/ReplicaStateMachine.scala
> +        val futureOfList = Future.sequence(listOfFutures)
Same here.

2016-12-22 14:38 UTC, resetius commented on core/src/main/scala/kafka/controller/ControllerChannelManager.scala
> -      result.put(topicPartition, PartitionStateInfo(leaderIsrAndControllerEpoch, replicas.toSet))
Futures answers can be reordered so we must check leaderEpoch here

2017-05-07 23:02 UTC, resetius commented
Rebased against trunk
ataraxer's suggestions applied

2017-05-08 01:00 UTC, resetius commented
parallel paritition creation added

2017-07-26 14:19 UTC, closed without merging