MINOR: update KTable JavaDoc
apache/kafka pull request #2438
Opened 2017-01-26 08:24 UTC by mjsax

2017-01-26 08:25 UTC, mjsax commented
@dguy @enothereska @guozhangwang

2017-01-26 09:47 UTC, dguy requested changes
Some typos/grammar changes

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/GlobalKTable.java
> + * This provides the ability to perform joins with {@link KStream} and {@link KTable}, without having to repartition the
We should actually remove the reference to `KTable` as we don't currently support it

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
>   * A {@link KTable} is either defined from one or multiple Kafka topics that are consumed message by message or
remove "or multiple"
Unless there is something i'm missing a `KTable` is created from exactly one topic unless it is the result of an aggregation

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Print the update records of this {@link KTable} to {@code System.out}.
Print the updated...

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * This function will use the generated name of the parent processor node to label the key/value pairs printed out
remove out

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * update record.
updated

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Print the update records of this {@link KTable} to {@code System.out}.
same as above

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Write the update records of this {@link KTable} to a file at the given path.
updated

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * This function will use the generated name of the parent processor node to label the key/value pairs printed out
written to the file

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Write the update records of this {@link KTable} to a file at the given path.
as above

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Write the update records of this {@link KTable} to a file at the given path.
As above

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Write the update records of this {@link KTable} to a file at the given path.
As above

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Perform an action on each update record of this {@link KTable}.
updated

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * {@link KTable} update record.
new or updated record?

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * For example, you can computes the new key as the length of the value string.
compute

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Materialize this changelog stream to a topic and creates a new {@link KTable} from the topic using default
This doesn't create a new `KTable`. It just writes the data to the topic

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Materialize this changelog stream to a topic and creates a new {@link KTable} from the topic.
As above

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Materialize this changelog stream to a topic and creates a new {@link KTable} from the topic using a customizable
As above

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * All data of this {@link KTable} will be redistributed through the repartitioning topic by writing all update
updated records to it, and re-reading all updated records from it,

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * All data of this {@link KTable} will be redistributed through the repartitioning topic by writing all update
as above

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * The join is computed by (1) updating the internal state if one {@link KTable} and (2) performing a lookup for a
if -> of ?
also add a , before and

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * For each {@link KTable} record that finds an corresponding record in the other {@link KTable} the provided
an -> a

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * update records to and rereading all update records from it, such that the join input {@link KTable} is
as above

2017-01-26 09:47 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * update records to and rereading all update records from it, such that the join input {@link KTable} is
as above

2017-01-26 21:29 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Print the update records of this {@link KTable} to {@code System.out}.
Was intended as is -- records are updates, so its an "update record" (or update-record). "updated" makes sense, too, though. Not sure what the better wording is...

2017-01-26 21:36 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Materialize this changelog stream to a topic and creates a new {@link KTable} from the topic using default
c&p error from `through`...

2017-01-26 21:39 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * The join is computed by (1) updating the internal state if one {@link KTable} and (2) performing a lookup for a
Why?
To my knowledge, for two things that are listed there is no comma: "A and B"
Only for three or more, there are command: "A, B, C, and D"

Correct my if I am wrong.

2017-01-26 21:51 UTC, dguy commented
Fair enough
On Thu, 26 Jan 2017 at 21:40, Matthias J. Sax <notifications@github.com>
wrote:

> *@mjsax* commented on this pull request.
> ------------------------------
>
> In streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> <https://github.com/apache/kafka/pull/2438>:
>
> > -     *
> -     * @param selector      select the grouping key and value to be aggregated
> -     * @param keySerde      key serdes for materializing this stream,
> -     *                      if not specified the default serdes defined in the configs will be used
> -     * @param valueSerde    value serdes for materializing this stream,
> -     *                      if not specified the default serdes defined in the configs will be used
> -     * @param <K1>          the key type of the {@link KGroupedTable}
> -     * @param <V1>          the value type of the {@link KGroupedTable}
> -     *
> -     * @return a {@link KGroupedTable} that contains the re-partitioned records of this {@link KTable}
> +     * Join records of this {@link KTable} with another {@link KTable}'s records using non-windowed inner equi join.
> +     * The join is a primary key join with join attribute {@code thisKTable.key == otherKTable.key}.
> +     * The result is an ever updating {@link KTable} that represents the <em>current</em> (i.e., processing time) result
> +     * of the join.
> +     * <p>
> +     * The join is computed by (1) updating the internal state if one {@link KTable} and (2) performing a lookup for a
>
> Why?
> To my knowledge, for two things that are listed there is no comma: "A and
> B"
> Only for three or more, there are command: "A, B, C, and D"
>
> Correct my if I am wrong.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/kafka/pull/2438>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADWLXXVYJ3srb9ok59OtUXsf3l_3pEDks5rWRKwgaJpZM4LuZIE>
> .
>

2017-01-27 01:53 UTC, mjsax commented
Addressed @dguy comments. (Not the part about "update records" -- but we can discuss if we want to reword).

Also added `KGroupedTable` and `GlobalKTable`.

Some minor refactoring in `KStream` (always discovering small issues along the way...)

Call for review @eno @guozhangwang

2017-01-27 05:38 UTC, guozhangwang commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * {@link KTable} update record.
I am OK with update records.

2017-01-27 07:47 UTC, mjsax commented
Rebased to resolve conflict.

2017-01-27 09:45 UTC, dguy commented on streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
> +     * Print the update records of this {@link KTable} to {@code System.out}.
I see what you mean. I just think "updated records" sounds more natural. But i'm not overly concerned

2017-01-27 09:47 UTC, dguy approved these changes

2017-01-27 16:41 UTC, guozhangwang commented
Merged to trunk and 0.10.2.

2017-01-27 16:41 UTC, closed without merging