KAFKA:4738 - Remove generic type of class ClientState
apache/kafka pull request #2616
Opened 2017-03-01 00:39 UTC by sharad-develop

Remove generic type of class ClientState and generic T inTaskAssignor.

2017-03-01 01:31 UTC, sharad-develop commented
retest this please

2017-03-01 03:07 UTC, sharad-develop commented
KAFKA:4738 - Remove generic type of class ClientState

2017-03-02 17:26 UTC, sharad-develop commented
This fixes - KAFKA:4738 - Remove generic type of class ClientState

2017-03-03 04:14 UTC, mjsax commented
Please update PR title to `KAFKA-4738:  Remove generic type of class ClientState`

Also please resolve merge conflict. Otherwise, we cannot review.

2017-03-04 18:00 UTC, sharad-develop commented
retest this please

2017-03-08 05:40 UTC, mjsax requested changes
Only some minor comments.

2017-03-08 05:40 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/StickyTaskAssignor.java
> +    private ClientState findClient(final TaskId taskId,
Nit: fix indention

2017-03-08 05:40 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/processor/internals/assignment/ClientStateTest.java
> +        client.assign(new TaskId(0, 1), true);
add a var `final TaskId tid = ...` (this should have been there for `int id = 1` already. Would improve the code base. Also for the other tests where it makes sense.

2017-03-08 18:16 UTC, sharad-develop commented
retest this please

2017-03-08 20:27 UTC, sharad-develop commented
retest this please

2017-03-08 20:46 UTC, mjsax commented
@sharad-develop It's ok of one test run fails -- no need to trigger a retest until all three pass. Just FYI.

2017-03-08 20:48 UTC, mjsax approved these changes
LGTM.
\cc @guozhangwang Call for final review and merging.

2017-03-10 19:28 UTC, guozhangwang approved these changes
Merged to trunk.

2017-03-10 19:28 UTC, closed without merging