KAFKA-4826. Fix some findbugs warnings in Kafka Streams
apache/kafka pull request #2623
Opened 2017-03-01 18:14 UTC by cmccabe

2017-03-01 21:06 UTC, mjsax requested changes

2017-03-01 21:06 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/kstream/Window.java
> +        if (obj == null)
Nit: add braces.

2017-03-01 21:06 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/kstream/Window.java
> +        if (obj == null)
Can you add a test to `WindowTest`.

2017-03-01 21:06 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDBStore.java
> +            throw new KafkaException(e);
Should this be `StreamsException` ?

2017-03-02 21:22 UTC, guozhangwang commented
@cmccabe Just in case you did not get the notifications..

2017-03-05 04:58 UTC, guozhangwang commented
test this please.

2017-03-05 06:31 UTC, guozhangwang commented on streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDBStore.java
> +            this.db = openDB(this.dbDir, this.options, TTL_SECONDS);
Just for my own benefits: what's the advantage of using `Files` here, and in line 173 below?

2017-03-05 17:54 UTC, guozhangwang commented on streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDBStore.java
> +            this.db = openDB(this.dbDir, this.options, TTL_SECONDS);
mvn, got some answers on SO..

2017-03-05 18:02 UTC, guozhangwang approved these changes
Merged to trunk. Thanks @cmccabe !!

2017-03-05 18:02 UTC, closed without merging