KAFKA-5096: Log invalid user configs and use defaults
apache/kafka pull request #2938
Opened 2017-04-28 19:38 UTC by johnma14

Kafka Streams do not allow users to modify some consumer configurations.
If the user modifies this property, currently an exception is thrown.
The following changes were made in this patch:
- Defined a new array 'NON_CONFIGURABLE_CONSUMER_CONFIGS' to hold the names
  of the configuration parameters that is not allowed to be modified. Currently, this
  contains just 1 parameter - enable_auto_commit. When the 'exactly once'
  feature is implemented ( KAFKA-4923), more parameters can be added to this
  array.
- Defined a new method 'checkIfUnexpectedUserSpecifiedConsumerConfig' to
  check if user overwrote the values of any of the non configurable configuration
  parameters. If so, then log a warning message and reset the default values
- Updated the javadoc to include the configuration parameters that cannot be
  modified by users.
- Updated the corresponding tests in StreamsConfigTest.java to reflect the changes
  made in StreamsConfig.java

2017-04-30 12:36 UTC, johnma14 commented
retest this please

2017-05-01 15:57 UTC, mjsax requested changes
Thanks for the PR!

Just some nitpick (but I guess it's important to phrase all messages carefully as it's user facing and thus must be crystal clear to give no room for miss interpretation).

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + * Kafka Streams require at least the following properties to be set:<br>
typo: `require[s]`

Nit: remove `<br>` -- the table markup below will start a new line anyway.

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + * <br>Kafka Streams do not allow the following properties to be overwritten (default values
typo: `do[es]`

Reword: `Kafka Streams does not allow to overwrite the following properties (Streams setting shown in parentheses)`

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +        // Streams do not allow users to configure certain consumer configurations, for example,
typo: `do[es]`

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +        // enable_auto_commit. In cases where user tries to override such non-configurable
nit: `enable.auto.commit`

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +        for (int index = 0; index < NON_CONFIGURABLE_CONSUMER_CONFIGS.length; index++) {
nit: add `final` -> `for (final int index...)` (in Streams code base, we try to use `final` whenever possible)

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +            String consumerConfig = NON_CONFIGURABLE_CONSUMER_CONFIGS[index];
nit: add `final`

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + *  <li>{@link ConsumerConfig#ENABLE_AUTO_COMMIT_CONFIG "enable.auto.commit"} &nbsp-&nbsp disabled by default</li>
Nit: I think we can improve the wording and simplify the markup (why do we need both `&nbsp`?). What about:

`<li>{@link ConsumerConfig#ENABLE_AUTO_COMMIT_CONFIG "enable.auto.commit"} (disabled)</li>`

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +                    + ", as the streams client will always use the default.");
Nit `"as Streams will always turn off auto committing."`

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +                log.warn("Unexpected user-specified consumer config  " + consumerConfig
Add `(user setting will be ignored)`

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +    private void checkIfUnexpectedUserSpecifiedConsumerConfig(Map clientProvidedProps) {
Nit: add `final` -> `(final Map clientProviderProps)` (in Streams code base, we try to use final whenever possible)

Add generics to `Map`

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +            if (clientProvidedProps.containsKey(consumerConfig)) {
Maybe we should only log, if the user specified value differs from Streams required values ?

2017-05-01 15:57 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/StreamsConfigTest.java
> +    public void shouldResetToDefaultIfConsumerAutoCommitIsOverridden() throws Exception {
Nit: I guess we can remove `throws` clause?

2017-05-01 15:57 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/StreamsConfigTest.java
> +    public void shouldResetToDefaultIfRestoreConsumerAutoCommitIsOverridden() throws Exception {
As above.

2017-05-01 15:57 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +                clientProvidedProps.remove(consumerConfig);
This should explicitly set Streams config value (we should not rely on consumer client default value that might change).

2017-05-01 18:06 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + * Kafka Streams require at least the following properties to be set:<br>
will do

2017-05-01 18:06 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + * <br>Kafka Streams do not allow the following properties to be overwritten (default values
will do. Thanks

2017-05-01 18:07 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + *  <li>{@link ConsumerConfig#ENABLE_AUTO_COMMIT_CONFIG "enable.auto.commit"} &nbsp-&nbsp disabled by default</li>
will do. Thanks.

2017-05-01 18:07 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +    private void checkIfUnexpectedUserSpecifiedConsumerConfig(Map clientProvidedProps) {
will do

2017-05-01 18:17 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +                clientProvidedProps.remove(consumerConfig);
@mjsax Thanks for your comments. Appreciate it. I just had a quick question about your comment here. So what I am doing here is removing the non-configurable property from the clientProvidedProps map. The streams config defaults for this parameter is set back in the getCommonConsumerConfigs method at: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java#L498 which is why I didn't set it again here. Is there something I am missing? Thanks @mjsax.

2017-05-01 18:19 UTC, johnma14 reviewed
Thanks @mjsax for your feedback. Appreciate it. I will make the changes you recommended. I just had a quick question on one of the comments which I have included in the review. Thanks again.

2017-05-03 20:10 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +                clientProvidedProps.remove(consumerConfig);
Ah I see. Makes sense. You can ignore my comment. Thanks for clarification.

2017-05-07 08:22 UTC, closed without merging

2017-05-17 05:09 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + * Kafka Streams require at least the following properties to be set:<br>
Done

2017-05-17 05:11 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + * <br>Kafka Streams do not allow the following properties to be overwritten (default values
Done

2017-05-17 05:15 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> + *  <li>{@link ConsumerConfig#ENABLE_AUTO_COMMIT_CONFIG "enable.auto.commit"} &nbsp-&nbsp disabled by default</li>
Done

2017-05-17 05:22 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +    private void checkIfUnexpectedUserSpecifiedConsumerConfig(Map clientProvidedProps) {
Done

2017-05-17 05:26 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +        // Streams do not allow users to configure certain consumer configurations, for example,
Done

2017-05-17 05:26 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +        // enable_auto_commit. In cases where user tries to override such non-configurable
Done

2017-05-17 05:33 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +        for (int index = 0; index < NON_CONFIGURABLE_CONSUMER_CONFIGS.length; index++) {
I used an enhanced for loop to iterate through a String array and also added final.

2017-05-17 05:33 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +            String consumerConfig = NON_CONFIGURABLE_CONSUMER_CONFIGS[index];
Done

2017-05-17 05:34 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +            if (clientProvidedProps.containsKey(consumerConfig)) {
Done

2017-05-17 05:35 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +                log.warn("Unexpected user-specified consumer config  " + consumerConfig
Done

2017-05-17 05:37 UTC, johnma14 commented on streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
> +                    + ", as the streams client will always use the default.");
Made the changes with some modifications to make the message generic enough for other configurations that could be added later.

2017-05-17 05:37 UTC, johnma14 commented on streams/src/test/java/org/apache/kafka/streams/StreamsConfigTest.java
> +    public void shouldResetToDefaultIfRestoreConsumerAutoCommitIsOverridden() throws Exception {
Done

2017-05-17 05:37 UTC, johnma14 commented on streams/src/test/java/org/apache/kafka/streams/StreamsConfigTest.java
> +    public void shouldResetToDefaultIfConsumerAutoCommitIsOverridden() throws Exception {
Done

2017-05-17 05:38 UTC, johnma14 reviewed
Made almost all the changes with some minor modifications to few of the recommendations. Thank you.