KAFKA-4750: RocksDBStore always deletes null values
apache/kafka pull request #3430
Opened 2017-06-26 09:26 UTC by evis

@guozhangwang @mjsax

2017-06-26 09:32 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5696/
Test FAILed (JDK 7 and Scala 2.11).

2017-06-26 09:33 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5682/
Test FAILed (JDK 8 and Scala 2.12).

2017-06-26 11:34 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5697/
Test PASSed (JDK 7 and Scala 2.11).

2017-06-26 11:56 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5683/
Test PASSed (JDK 8 and Scala 2.12).

2017-06-26 17:10 UTC, mjsax requested changes
Thanks for the patch and the test!

Just a couple of nits :)

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +                    return "not-null".getBytes();
Nit: I think `"not-null"` might be confusion. I think a better naming would be `"null-encoding-that-is-not-just-'null'"`

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +        File dir = TestUtils.tempDirectory();
Nit: `dir` only used once -- can be removed

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +        context = new MockProcessorContext(dir,
NIt: fix indention -- either move `dir` to next line, or align other parameters with `dir` starting column.

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +        Serde<String> serde = Serdes.serdeFrom(serializer, new StringDeserializer());
Nit: can be `final`

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +        Serializer<String> serializer = new StringSerializer() {
Nit: can be `final`

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +            public byte[] serialize(String topic, String data) {
Nit: both parameters can be `final`

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +        KeyValueIterator<String, String> it = subject.all();
Nit: can be `final`

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +            KeyValue<String, String> next = it.next();
Nit: can be `final`

2017-06-26 17:10 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/state/internals/RocksDBStoreCustomNullSerdeTest.java
> +            if (next.key.equals("a"))
Nit: Please use `{ }` (even for one line blocks)

2017-06-26 20:18 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/5700/
Test PASSed (JDK 8 and Scala 2.12).

2017-06-26 21:11 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/5714/
Test PASSed (JDK 7 and Scala 2.11).

2017-06-26 21:19 UTC, mjsax approved these changes
LGTM.

Call for review and merging @guozhangwang @dguy

2017-06-26 23:17 UTC, guozhangwang commented
@evis @mjsax I have some more thoughts commented on the ticket itself: I'm wondering if we should just not using `put(key, null)` to implement `delete(key)` since our java doc doe not enforce that a `null` value (note this value is null object, not underlying null byte arrays) indicates deletion.

2018-02-01 20:47 UTC, guozhangwang commented
I'm closing this PR and continue working on https://github.com/apache/kafka/pull/4508.

2018-02-01 20:47 UTC, closed without merging