MINOR: enforce setting listeners in CREATE state.
apache/kafka pull request #3569
Opened 2017-07-24 22:40 UTC by bbejeck

2017-07-24 22:42 UTC, bbejeck commented
@dguy @guozhangwang @mjsax follow on PR from #3325 to enforce only setting `UncaughtExceptionHandler` and `StateListener` in `CREATE` state.

2017-07-24 23:25 UTC, guozhangwang commented on streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java
> +                throw new IllegalStateException("Can only set UncaughtExceptionHandler in CREATE state.");
nit `CREATE` -> `CREATED`.

2017-07-25 06:12 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6322/
Test PASSed (JDK 7 and Scala 2.11).

2017-07-25 06:13 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6306/
Test PASSed (JDK 8 and Scala 2.12).

2017-07-25 14:46 UTC, bbejeck commented on streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java
> +                throw new IllegalStateException("Can only set UncaughtExceptionHandler in CREATE state.");
Ack

2017-07-25 14:46 UTC, bbejeck commented
@guozhangwang updated per comment.

2017-07-25 15:45 UTC, mjsax requested changes
Some comments about the tests. Otherwise LGTM.

2017-07-25 15:45 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/KafkaStreamsTest.java
> +    @Test(expected = IllegalStateException.class)
We should not expect an exception here but add a `fail(...)` after `streams.setUncaughtExceptionHandler(null);` -- and thus, not rethrow within catch.

2017-07-25 15:45 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/KafkaStreamsTest.java
> +    @Test(expected = IllegalStateException.class)
As above.

2017-07-25 20:22 UTC, bbejeck commented on streams/src/test/java/org/apache/kafka/streams/KafkaStreamsTest.java
> +    @Test(expected = IllegalStateException.class)
Ack

2017-07-25 20:23 UTC, bbejeck commented on streams/src/test/java/org/apache/kafka/streams/KafkaStreamsTest.java
> +    @Test(expected = IllegalStateException.class)
Ack

2017-07-25 20:43 UTC, bbejeck commented
comments addressed

2017-07-25 21:46 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk7-scala2.11/6329/
Test PASSed (JDK 7 and Scala 2.11).

2017-07-25 21:56 UTC, asfgit commented
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/kafka-pr-jdk8-scala2.12/6314/
Test PASSed (JDK 8 and Scala 2.12).

2017-07-26 08:06 UTC, dguy approved these changes
Thanks @bbejeck, LGTM

2017-07-26 08:08 UTC, dguy commented
Merged to trunk

2017-07-26 08:09 UTC, closed without merging