KAFKA-6138 Simplify StreamsBuilder#addGlobalStore
apache/kafka pull request #4430
Opened 2018-01-17 02:39 UTC by panuwat-sc

deprecated StreamsBuilder#addGlobalStore and InternalStreamsBuilder#addGlobalStore
add new StreamsBuilder#addGlobalStore and InternalStreamsBuilder#addGlobalStore without sourceName and processorName as parameter
generate sourceName and processorName by using InternalStreamsBuilder#newProcessorName

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

2018-01-17 18:17 UTC, mjsax requested changes
Thanks for the PR. Some initial comments.

2018-01-17 18:17 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/StreamsBuilderTest.java
> +        KeyValueStoreBuilder t = new KeyValueStoreBuilder();
This line fails in the build and needs a fix.

2018-01-17 18:17 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsBuilder.java
> +    @Deprecated
We should extend the JavaDoc, with `@deprecated` annotation to, and point to the new method that should be used.

2018-01-17 18:17 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/StreamsBuilder.java
> +    /**
Nit: missing empty line

2018-01-17 18:17 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/kstream/internals/InternalStreamsBuilder.java
> +    @Deprecated
This is an internal class -- no need to mark as deprecated.

2018-01-17 18:17 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/kstream/internals/InternalStreamsBuilder.java
> +        // explicitly disable logging for global stores
we should not copy the code from the old `addGlobalStore()` but rather call the old `addGlobalStore()` passing the generated names.

2018-01-27 00:20 UTC, mjsax commented
Retest this please.

2018-01-27 00:21 UTC, mjsax approved these changes
Just two nits. Otherwise LGTM.

Call for second review @bbejeck @dguy @guozhangwang

2018-01-27 00:21 UTC, mjsax commented on streams/src/main/java/org/apache/kafka/streams/kstream/internals/InternalStreamsBuilder.java
> +    public synchronized void addGlobalStore(final StoreBuilder<KeyValueStore> storeBuilder,
Nit: add empty line

2018-01-27 00:21 UTC, mjsax commented on streams/src/test/java/org/apache/kafka/streams/StreamsBuilderTest.java
> +
nit: revert

2018-01-30 17:23 UTC, mjsax commented
@dguy @bbejeck @guozhangwang Can we get a second review? If not merged today, it won't be included in 1.1. @panuwat-sc You will need to address all comments today so we can get it into 1.1 release.

2018-01-30 17:52 UTC, bbejeck approved these changes
Thanks for PR, LGTM

2018-01-30 21:50 UTC, mjsax commented
Retest this please.

2018-01-31 10:15 UTC, dguy commented
retest this please

2018-01-31 21:53 UTC, merged

2018-01-31 21:53 UTC, mjsax commented
Merged to `trunk` -- will be part of `1.1` release.

Thanks for the KIP and patch @panuwat-sc !