KAFKA-9435: DescribeLogDirs automated protocol
apache/kafka pull request #7972
Opened 2020-01-16 12:12 UTC by tombentley

Also add version 2 to make use of flexible versions, per KIP-482.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

2020-01-16 12:13 UTC, tombentley commented
@cmccabe are you able to review this?

2020-02-06 14:21 UTC, mimaison requested changes
Thanks for the PR. I've made a very quick first pass and left a few comments

2020-02-06 14:21 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
> +                ArrayList<Integer> v = new ArrayList<>();
The left side should be `List`

2020-02-06 14:21 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeLogDirsRequest.java
> +    private final short version;
Like in https://github.com/apache/kafka/pull/7957 let's remove this field

2020-02-06 14:21 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
> +                ArrayList<Integer> v = new ArrayList<>();
Also can we find a better name? What about `partitionIndex`?

2020-02-25 12:08 UTC, tombentley commented
@mimaison done, if you want to do another pass.

2020-03-13 18:00 UTC, mimaison requested changes
I've made a quick pass and left a few comments.
Can you also rebase on trunk?

2020-03-13 18:00 UTC, mimaison commented on core/src/test/scala/unit/kafka/server/RequestQuotaTest.scala
> +            .setPartitionIndex(Collections.singletonList(tp.partition())))
We can remove a bunch of brackets in this statement

2020-03-13 18:00 UTC, mimaison commented on core/src/main/scala/kafka/server/ReplicaManager.scala
> +          new DescribeLogDirsResponseData.DescribeLogDirsResult().setLogDir(absolutePath)
I think it's slightly more readable if each setter is called on a new line. There're a few places where `setLogDir()` is called inline in this file.

2020-03-13 18:00 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeLogDirsResponse.java
>       */
Is this comment still acurate?

2020-03-17 16:14 UTC, tombentley commented
@mimaison fixed review comments and rebased.

2020-03-19 14:28 UTC, mimaison requested changes
I've made another pass and spotted a couple of tiny issues. Happy to merge once fixed

2020-03-19 14:28 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeLogDirsRequest.java
>      // topicPartitions == null indicates requesting all partitions, and an empty list indicates requesting no partitions.
This comment can now be removed

2020-03-19 14:28 UTC, mimaison commented on core/src/main/scala/kafka/server/ReplicaManager.scala
> +import org.apache.kafka.common.message.DescribeLogDirsResponseData._
nit: Can we put this with the other import from the same package

2020-03-19 14:39 UTC, tombentley commented
@mimaison done

2020-03-19 15:10 UTC, mimaison requested changes
I've left a couple of new comments for issues we should fix

2020-03-19 15:10 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeLogDirsRequest.java
>                      TOPIC_NAME,
This V0 schema should be deleted too

2020-03-19 15:10 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeLogDirsRequest.java
> +    public DescribeLogDirsRequest(DescribeLogDirsRequestData data, short version) {
The comment above is out of date

2020-03-19 15:21 UTC, tombentley commented
Sloppy! Thanks, now fixed.

2020-03-19 15:25 UTC, mimaison approved these changes

2020-03-19 15:26 UTC, merged