KAFKA-9432 automated protocol for DescribeConfigs
apache/kafka pull request #8312
Opened 2020-03-18 17:47 UTC by tombentley

Change the DescribeConfigs request and response to use the generated protocol messages.

2020-03-18 17:49 UTC, tombentley commented
@mimaison here's another one, grateful if you could review.

2020-04-09 12:38 UTC, tombentley commented
Rebased for conflict.

2020-04-09 14:58 UTC, tombentley commented
Rebased for conflict.

2020-04-28 09:04 UTC, tombentley commented
Rebased for conflict.

2020-05-12 10:33 UTC, tombentley commented
Rebased for conflict.

2020-05-22 11:00 UTC, mimaison commented
retest this please

2020-05-22 12:16 UTC, mimaison requested changes
@tombentley Thanks for the PR. I've made a first pass and left a bunch of comments

2020-05-22 12:16 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
> +                    return new DescribeConfigsRequest.Builder(unifiedRequestResources.setIncludeSynoyms(options.includeSynonyms()));
I wonder if it would read better if `unifiedRequestResources` was instead a `List<DescribeConfigsResource>` and we were creating the `DescribeConfigsRequestData` object and calling all its setters here. WDYT?

2020-05-22 12:16 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeConfigsRequest.java
> +                    Errors error = Errors.forException(e);
Can we move that line to the top?

2020-05-22 12:16 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeConfigsResponse.java
> +                for (DescribeConfigsResponseData.DescribeConfigsResourceResult x : result.configs()) {
Let's give that variable a better name, what about `config`?

2020-05-22 12:16 UTC, mimaison commented on clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
> +                        .setErrorCode(ApiError.NONE.error().code())
We can use `Errors.NONE.code()` directly. Same below

2020-05-22 12:16 UTC, mimaison commented on core/src/main/scala/kafka/server/AdminManager.scala
> +        new DescribeConfigsResponseData.DescribeConfigsResult().setErrorCode(ApiError.NONE.error().code())
We can use `Errors.NONE.code` directly

2020-05-22 12:16 UTC, mimaison commented on core/src/main/scala/kafka/server/AdminManager.scala
> +        .filter(perBrokerConfig || _.source == ConfigSource.DYNAMIC_DEFAULT_BROKER_CONFIG.id())
No need for the brackets after `id`

2020-05-22 12:16 UTC, mimaison commented on core/src/main/scala/kafka/server/KafkaApis.scala
> +      val error = ConfigResource.Type.forId(resource.resourceType()) match {
We can remove the brackets here. Same a few lines below after `resourceName`

2020-05-22 12:16 UTC, mimaison commented on clients/src/main/resources/common/message/DescribeConfigsRequest.json
> +  // Version 1 adds IncludeSynonyms.
Let's also fix the field name

2020-05-22 12:16 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
> +    private Config describeConfigResult(DescribeConfigsResponseData.DescribeConfigsResult describeConfigsResult) {
It looks like we are not calling `configSynonyms()` anymore, so we can remove that private method

2020-05-22 12:16 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
> +                        for (DescribeConfigsResponseData.DescribeConfigsResult resultData : response.data().results()) {
We are not using `resultData` in this loop. Is that expected?

2020-05-22 12:16 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeConfigsRequest.java
> +            this.data = data;
As we remove the other constructors, `toResourceToConfigNames` is not called anymore. Let's delete it

2020-05-22 12:16 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeConfigsResponse.java
> +        UNKNOWN_CONFIG((byte) 0, org.apache.kafka.clients.admin.ConfigEntry.ConfigSource.UNKNOWN),
It's unfortunate the public enum cannot do the mapping and we have to keep a copy here. Could we maybe rename this one so this looks less crazy? WDYT?

2020-05-27 14:38 UTC, tombentley commented
@mimaison I've fixed those, if you want to make a 2nd pass. I guess I should add a test to `KafkaAdminClientTest` too.

2020-05-28 08:42 UTC, mimaison commented
retest this please

2020-06-04 09:53 UTC, mimaison commented
Let's get https://github.com/apache/kafka/pull/8311 merged first and then rebase this one on top

2020-06-08 15:26 UTC, tombentley commented
@mimaison I've rebased and added some more tests in KafkaAdminClientTest. In so doing I noticed that `describeConfigs()` would require two requests to each broker when both `BROKER` and `BROKER_LOGGER` config resources for a broker were requested. I've fixed that, but `alterConfigs()` and `incrementalAlterConfigs()` do the same thing. WDYT about changing them too?

2020-06-08 15:36 UTC, tombentley commented
This PR will also fix [KAFKA-6962](https://issues.apache.org/jira/browse/KAFKA-6962)

2020-06-08 20:58 UTC, mimaison commented
retest this please

2020-06-11 11:08 UTC, mimaison requested changes
Thanks for the updates. It looks good. I just left a few minor comments.

2020-06-11 11:08 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
> -                                configSynonyms(configEntry), configType(configEntry.type()), configEntry.documentation()));
It looks like `configType()` is not used anymore. Can we delete it?

2020-06-11 11:08 UTC, mimaison commented on core/src/main/scala/kafka/server/KafkaApis.scala
> +        .setConfigs(util.Collections.emptyList[DescribeConfigsResponseData.DescribeConfigsResourceResult])
We can drop `util` here, we are importing `import java.util.{Collections, Optional}`

2020-06-11 11:08 UTC, mimaison commented on clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
> +                    value = new HashMap<>(broker != null ? 2 : 16);
I wonder if we can just get a Map with the default size. I don't expect this code path to be very hot

2020-06-11 18:43 UTC, tombentley commented
@mimaison done.

2020-06-12 20:17 UTC, mimaison approved these changes

2020-06-12 20:19 UTC, merged

2020-06-13 00:53 UTC, ableegoldman commented on clients/src/main/java/org/apache/kafka/common/requests/DescribeConfigsResponse.java
> -        this.configs = Objects.requireNonNull(configs, "configs");
Hey @mimaison @tombentley, removing this constructor seems to have broken the build (it was used in `TopicAdminTest`). Can we get a hotfix for this to unblock other PRs?

2020-06-13 08:13 UTC, tombentley commented
@ableegoldman sorry about that. A fix has now been committed to trunk. Thanks to @chia7712.

2020-07-18 12:51 UTC, omkreddy commented
@tombentley After this change, `adminClient.describeConnfigs()` is not compatible with older kafka broker versions. 
It seems, older brokers are receiving empty configNames [here](https://github.com/apache/kafka/blob/2.5/core/src/main/scala/kafka/server/AdminManager.scala#L355). Older brokers expect `Option.None` value.  Due to this old brokers are returning empty config list.  We may need to explicitly set `setConfigurationKeys(null)` [here](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L1952).

We also need to update ClientCompatibilityTest, to catch these kind of errors.
https://github.com/apache/kafka/blob/trunk/tools/src/main/java/org/apache/kafka/tools/ClientCompatibilityTest.java
https://github.com/apache/kafka/blob/trunk/tests/kafkatest/tests/client/client_compatibility_features_test.py

Let me know, if you can help with the fix.

cc @mimaison

2020-07-28 07:37 UTC, tombentley commented
@omkreddy sorry about that, I was away. I see that you fixed it in the meantime.

2020-07-28 08:10 UTC, tombentley commented
@omkreddy, also thanks for the pointer to that compatibility test, I wasn't previously aware of it, but I'll use it now that I am.