KAFKA-10460: ReplicaListValidator format checking is incomplete
apache/kafka pull request #9326
Opened 2020-09-23 11:47 UTC by ankit-kumar-25

What? :: See https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/server/ConfigHandler.scala#L220 . The logic is supposed to accept only two cases:

list of k:v pairs
a single '*'
But in practice, since the disjunction's second part only checks that the head is '*', the case where a k:v list is headed by a star is also accepted (and then later broker dies at startup, refusing the value).

JIRA: https://issues.apache.org/jira/browse/KAFKA-10460

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

2020-09-29 08:58 UTC, viktorsomogyi requested changes
It looks like you have some test failures. Would you please check them?

2020-10-07 08:22 UTC, ankit-kumar-25 commented
@viktorsomogyi, the tests are passing after the last commit. Can you please review it?

2020-11-23 08:34 UTC, viktorsomogyi approved these changes

2020-11-23 08:34 UTC, viktorsomogyi commented
@mimaison would you please quickly review this?

2020-11-26 11:00 UTC, mimaison commented
@ankit-kumar-25 Thanks for the PR. Can you add a test?

2020-11-30 12:21 UTC, ankit-kumar-25 commented
Hey @mimaison, Thank you for your input. I have added a couple of test cases to validate this condition. 

For some reason the `Build Failed`. Can you please review the change and re-run the test/build if feasible?

2020-12-03 10:32 UTC, mimaison commented
Thanks for the update. The changes looks fine. 
I've rekicked the build and I'll merge if it passes

2020-12-03 14:35 UTC, mimaison commented
Travis/Jenkins are having issues. I ran all tests locally and they passed.

2020-12-03 14:35 UTC, mimaison approved these changes

2020-12-03 14:36 UTC, merged